export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE"
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE"

export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const DELETE_USER = "DELETE_USER"
export const ADD_USER = "ADD_USER"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"


export const STORE_PRODUCTS = "STORE_PRODUCTS"
export const STORE_USERS = "STORE_USERS"

export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN"
